/**
 * WASM Filter Engine
 *
 * Provides a TypeScript interface to the Rust/WASM image processing core.
 * Falls back to JavaScript implementations if WASM is not available.
 */

import type { FilterParams } from '../state/types';

// WASM module types (will be generated by wasm-pack)
interface WasmModule {
  ImageBuffer: new (width: number, height: number, data: Uint8Array) => ImageBufferWasm;
  processBrightnessInPlace: (pixels: Float32Array, amount: number) => void;
  processContrastInPlace: (pixels: Float32Array, amount: number) => void;
  processSaturationInPlace: (pixels: Float32Array, amount: number) => void;
  processGrayscaleInPlace: (pixels: Float32Array) => void;
  processSepiaInPlace: (pixels: Float32Array) => void;
  processInvertInPlace: (pixels: Float32Array) => void;
}

interface ImageBufferWasm {
  brightness: (amount: number) => void;
  contrast: (amount: number) => void;
  saturation: (amount: number) => void;
  blur: (radius: number) => void;
  grayscale: () => void;
  sepia: () => void;
  invert: () => void;
  toUint8Array: () => Uint8Array;
  free: () => void;
}

export class WasmFilterEngine {
  private wasmModule: WasmModule | null = null;
  private isInitialized = false;
  private initPromise: Promise<boolean> | null = null;

  /**
   * Initialize the WASM module
   * @returns Promise that resolves to true if WASM is available, false otherwise
   */
  async init(): Promise<boolean> {
    if (this.isInitialized) return this.wasmModule !== null;
    if (this.initPromise) return this.initPromise;

    this.initPromise = this.loadWasmModule();
    return this.initPromise;
  }

  private async loadWasmModule(): Promise<boolean> {
    try {
      // Dynamic import of WASM module (will be built by wasm-pack)
      const wasm = await import('../../wasm/faux_toe_shop_wasm');
      await wasm.default(); // Initialize
      this.wasmModule = wasm as unknown as WasmModule;
      this.isInitialized = true;
      console.log('[WasmFilterEngine] WASM module loaded successfully');
      return true;
    } catch (error) {
      console.warn('[WasmFilterEngine] WASM not available, using JS fallback:', error);
      this.isInitialized = true;
      return false;
    }
  }

  /**
   * Check if WASM is available
   */
  get isWasmAvailable(): boolean {
    return this.wasmModule !== null;
  }

  /**
   * Apply filters to image data
   *
   * @param imageData - Canvas ImageData object
   * @param params - Filter parameters
   * @returns Processed ImageData
   */
  async applyFilters(imageData: ImageData, params: FilterParams): Promise<ImageData> {
    await this.init();

    if (this.wasmModule) {
      return this.applyFiltersWasm(imageData, params);
    } else {
      return this.applyFiltersJS(imageData, params);
    }
  }

  private applyFiltersWasm(imageData: ImageData, params: FilterParams): ImageData {
    const { width, height, data } = imageData;
    const buffer = new this.wasmModule!.ImageBuffer(width, height, new Uint8Array(data));

    try {
      // Apply filters in order
      if (params.brightness !== undefined && params.brightness !== 0) {
        buffer.brightness(params.brightness);
      }
      if (params.contrast !== undefined && params.contrast !== 0) {
        buffer.contrast(params.contrast);
      }
      if (params.saturation !== undefined && params.saturation !== 0) {
        buffer.saturation(params.saturation);
      }
      if (params.blur !== undefined && params.blur > 0) {
        buffer.blur(params.blur);
      }
      if (params.grayscale) {
        buffer.grayscale();
      }
      if (params.sepia) {
        buffer.sepia();
      }
      if (params.invert) {
        buffer.invert();
      }

      // Get result
      const resultData = buffer.toUint8Array();
      return new ImageData(new Uint8ClampedArray(resultData), width, height);
    } finally {
      buffer.free();
    }
  }

  /**
   * JavaScript fallback implementations
   */
  private applyFiltersJS(imageData: ImageData, params: FilterParams): ImageData {
    const data = new Uint8ClampedArray(imageData.data);

    if (params.brightness !== undefined && params.brightness !== 0) {
      this.brightnessJS(data, params.brightness);
    }
    if (params.contrast !== undefined && params.contrast !== 0) {
      this.contrastJS(data, params.contrast);
    }
    if (params.saturation !== undefined && params.saturation !== 0) {
      this.saturationJS(data, params.saturation);
    }
    if (params.grayscale) {
      this.grayscaleJS(data);
    }
    if (params.sepia) {
      this.sepiaJS(data);
    }
    if (params.invert) {
      this.invertJS(data);
    }
    // Note: Blur is expensive in JS, skip for fallback or implement simple version

    return new ImageData(data, imageData.width, imageData.height);
  }

  private brightnessJS(data: Uint8ClampedArray, amount: number): void {
    const adjustment = amount * 255;
    for (let i = 0; i < data.length; i += 4) {
      data[i] = Math.max(0, Math.min(255, data[i] + adjustment));
      data[i + 1] = Math.max(0, Math.min(255, data[i + 1] + adjustment));
      data[i + 2] = Math.max(0, Math.min(255, data[i + 2] + adjustment));
    }
  }

  private contrastJS(data: Uint8ClampedArray, amount: number): void {
    const factor = 1 + amount;
    for (let i = 0; i < data.length; i += 4) {
      data[i] = Math.max(0, Math.min(255, (data[i] - 128) * factor + 128));
      data[i + 1] = Math.max(0, Math.min(255, (data[i + 1] - 128) * factor + 128));
      data[i + 2] = Math.max(0, Math.min(255, (data[i + 2] - 128) * factor + 128));
    }
  }

  private saturationJS(data: Uint8ClampedArray, amount: number): void {
    const factor = 1 + amount;
    for (let i = 0; i < data.length; i += 4) {
      const r = data[i], g = data[i + 1], b = data[i + 2];
      const gray = 0.2126 * r + 0.7152 * g + 0.0722 * b;
      data[i] = Math.max(0, Math.min(255, gray + (r - gray) * factor));
      data[i + 1] = Math.max(0, Math.min(255, gray + (g - gray) * factor));
      data[i + 2] = Math.max(0, Math.min(255, gray + (b - gray) * factor));
    }
  }

  private grayscaleJS(data: Uint8ClampedArray): void {
    for (let i = 0; i < data.length; i += 4) {
      const gray = 0.2126 * data[i] + 0.7152 * data[i + 1] + 0.0722 * data[i + 2];
      data[i] = data[i + 1] = data[i + 2] = gray;
    }
  }

  private sepiaJS(data: Uint8ClampedArray): void {
    for (let i = 0; i < data.length; i += 4) {
      const r = data[i], g = data[i + 1], b = data[i + 2];
      data[i] = Math.min(255, r * 0.393 + g * 0.769 + b * 0.189);
      data[i + 1] = Math.min(255, r * 0.349 + g * 0.686 + b * 0.168);
      data[i + 2] = Math.min(255, r * 0.272 + g * 0.534 + b * 0.131);
    }
  }

  private invertJS(data: Uint8ClampedArray): void {
    for (let i = 0; i < data.length; i += 4) {
      data[i] = 255 - data[i];
      data[i + 1] = 255 - data[i + 1];
      data[i + 2] = 255 - data[i + 2];
    }
  }

  /**
   * Process Float32Array directly (for use with binary state)
   * More efficient as it avoids Uint8 conversion
   */
  async processFloat32InPlace(pixels: Float32Array, params: FilterParams): Promise<void> {
    await this.init();

    if (this.wasmModule) {
      if (params.brightness !== undefined && params.brightness !== 0) {
        this.wasmModule.processBrightnessInPlace(pixels, params.brightness);
      }
      if (params.contrast !== undefined && params.contrast !== 0) {
        this.wasmModule.processContrastInPlace(pixels, params.contrast);
      }
      if (params.saturation !== undefined && params.saturation !== 0) {
        this.wasmModule.processSaturationInPlace(pixels, params.saturation);
      }
      if (params.grayscale) {
        this.wasmModule.processGrayscaleInPlace(pixels);
      }
      if (params.sepia) {
        this.wasmModule.processSepiaInPlace(pixels);
      }
      if (params.invert) {
        this.wasmModule.processInvertInPlace(pixels);
      }
    } else {
      // JS fallback for Float32Array
      this.processFloat32JS(pixels, params);
    }
  }

  private processFloat32JS(pixels: Float32Array, params: FilterParams): void {
    if (params.brightness !== undefined && params.brightness !== 0) {
      for (let i = 0; i < pixels.length; i += 4) {
        pixels[i] = Math.max(0, Math.min(1, pixels[i] + params.brightness));
        pixels[i + 1] = Math.max(0, Math.min(1, pixels[i + 1] + params.brightness));
        pixels[i + 2] = Math.max(0, Math.min(1, pixels[i + 2] + params.brightness));
      }
    }
    // Add other filter implementations as needed
  }
}

// Singleton instance
export const wasmFilterEngine = new WasmFilterEngine();
